# Generated by Django 4.2.2 on 2024-08-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readers',
            new_name='Reader',
        ),
    ]
