# Generated by Django 4.2.2 on 2024-08-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryportal', '0002_rename_readers_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
